//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreJoiningFinalAssignment
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProductsdbEntities : DbContext
    {
        public ProductsdbEntities()
            : base("name=ProductsdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Log> Log { get; set; }

        public System.Data.Entity.DbSet<PreJoiningFinalAssignment.Models.ProductView> ProductViews { get; set; }

        public System.Data.Entity.DbSet<PreJoiningFinalAssignment.Models.UserRegistration> UserRegistrations { get; set; }
    }
}
